---
- name: provisioning builder
  hosts: builder
  become: yes

  tasks:
  - name: Ensure jdk package is present
    apt:
     name: default-jdk
     state: present
  
  - name: Ensure maven package is present
    apt:
     name: maven
     state: present

  - name: Ensure git package is present
    apt:
     name: git
     state: present
  - name: clone java project
    git:
      repo: https://github.com/santoshkatageri/Java-Mysql-Simple-Login-Web-application.git
      dest: /home/ubuntu/jdk/Login
      clone: yes
      update: yes
  - name: build app
    shell: cd /home/ubuntu/jdk/Login; mvn package

  - name: ensure private key and public one are present
     copy: 
       src: /home/allon/.ssh/ 
       dest: "/home/ubuntu/.ssh/{{ item }}" 
       mode: 0600
      with_items:
        - app_keys/id_dsa.pub
        - app_keys/id_dsa




- name: provisioning prod
  hosts: prod
  become: yes

  tasks: 
  - name: Ensure tomcat package is present
    apt:
     name: tomcat9
     state: present


- name: provisioning builder
  hosts: builder
  become: yes
  
  tasks:
  - name: Ensure LoginWebApp.war is present
    synchronize:
     src: /home/ubuntu/jdk/Login/targer
     dest: rsync://37.139.35.41/var/lib/tomcat9/webapps

- name: provisioning prod
  hosts: prod
  become: yes

  tasks: 
  - name: Ensure tomcat service is started
    service:
     name: tomcat
     state: started

   
