---
- name: provisioning builder
  hosts: builder
  become: yes

  tasks:
  - name: Ensure jdk package is present
    apt:
     name: default-jdk
     state: present
  
  - name: Ensure maven package is present
    apt:
     name: maven
     state: present

  - name: Ensure git package is present
    apt:
     name: git
     state: present
  - name: clone java project
    git:
      repo: https://github.com/santoshkatageri/Java-Mysql-Simple-Login-Web-application.git
      dest: /home/ubuntu/jdk/Login
      clone: yes
      update: yes
  - name: build app
    shell: cd /home/ubuntu/jdk/Login; mvn package

  - name: copy ssh key to builder
    ansible.builtin.copy:
      src: /home/allon/.ssh/id_rsa
      dest: /home/allon/.ssh/
      owner: allon
      group: allon
      mode: '0644'
  
  #- name: ensure private key and public one are present
  #  copy: 
  #    src: /home/allon/.ssh/ 
  #    dest: "/home/ubuntu/.ssh/{{ item }}" 
  #    mode: 0600
  #    with_items:
  #      - app_keys/id_dsa.pub
  #      - app_keys/id_dsa




- name: provisioning prod
  hosts: prod
  become: yes

  tasks: 
  - name: Ensure tomcat package is present
    apt:
     name: tomcat9
     state: present


- name: provisioning builder
  hosts: builder
  become: yes
  
  tasks:
  - name: Ensure LoginWebApp.war is present
    synchronize:
     src: /home/ubuntu/jdk/Login/targer
     dest: rsync://158.160.81.90/var/lib/tomcat9/webapps
    delegate_to: builder

- name: provisioning prod
  hosts: prod
  become: yes

  tasks: 
  - name: Ensure tomcat service is started
    service:
     name: tomcat
     state: started

   
