---
- name: provisioning builder
  hosts: builder
  become: yes

  tasks:
  - name: Ensure jdk package is present
    apt:
     name: default-jdk
     state: present
  
  - name: Ensure maven package is present
    apt:
     name: maven
     state: present

  - name: Ensure git package is present
    apt:
     name: git
     state: present
  - name: clone java project
    git:
      repo: https://github.com/santoshkatageri/Java-Mysql-Simple-Login-Web-application.git
      dest: /home/ubuntu/jdk
      clone: yes
      update: yes
  - name: build app
    shell: cd /home/ubuntu/jdk/Java-Mysql-Simple-Login-Web-application; chmod -R 777 ./; mvn package
  - name: transport war 
    synchronize:
     src: /home/ubuntu/jdk/Java-Mysql-Simple-Login-Web-application/targer/LoginWebApp.war
     dest: /home/ubuntu/ansible_pr
     mode: push

- name: provisioning prod
  hosts: prod
  become: yes

  tasks: 
  - name: Ensure tomcat package is present
    apt:
     name: tomcat9
     state: present

  - name: Ensure LoginWebApp.war is present
    synchronize:
     src: LoginWebApp.war
     dest: /usr/local/tomcat9/webapps
     mode: pull
  - name: Ensure tomcat service is started
    service:
     name: tomcat
     state: started